# Site
name: 'News Noir Meilleur'
description: "Toute l'actualité de l'Afrique et de sa diaspora."
logo: 'assets/icons/icon.png'
favicon: 'assets/icons/icon.png'
baseurl: ''
#baseurl: 'https://news.noirmeilleur.com'
disqus: 'news-noir-meilleur'
email: 'elisis.author@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

authors:
  elisis:
    name: Bienvenu Kokou AGBAVON
    avatar: "assets/avatars/me.jpg"
    display_name: Kokou AGBAVON
    gravatar: c9908ff7b5184aae488be00a62a75c27
    email: elisis.author@gmail.com
    site: https://bienvenuelisis.github.io/
    twitter: https://twitter.com/AgbavonB
    social: https://www.linkedin.com/in/bienvenu-agbavon/
    bio: "A Java Backend Programmer. IT Ingenior. Humanist blogger. African optimist"

amazonAds:
  nm:
    tab: [1, 2, 3, 4, 5]
  books:
    tab: [1, 2]

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: elisis
      avatar: /assets/avatars/me.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 7



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, /.history]